# Generated by Django 5.2.8 on 2025-12-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_estado_marca_modelo_alter_cliente_options_and_more'),
        ('mainApp', '0008_alter_cliente_telefono'),
    ]

    operations = [
    ]
