# Generated by Django 5.2.8 on 2025-12-23 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_merge_20251222_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_de_trabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApp.cliente'),
        ),
    ]
